fix: py.typed module ignored when building package
keleshev/schema pull request #317
Opened 2024-06-03 12:54 UTC by maximeflya

fixes #316

Moved from a single module to a package in order for the `py.typed` file to be included

I tested building the package using python 3.8 and installed it. Mypy was able to read the package's types and it works without any code changes.

I manually checked that the `py.typed` file was stored in the wheel and in the `tar.gz` package

I ran `pytest` in python 3.8 and everything passed

2024-06-03 12:56 UTC, skorokithakis requested changes

2024-06-03 15:44 UTC, skorokithakis commented on .gitignore
> +# Virtual environment
I can't think of any reason anyone would want to commit a file called venv, so that's probably OK.

2024-06-03 15:45 UTC, skorokithakis commented on setup.py
> +version_file = os.path.join("schema", "__init__.py")
Yeah, agreed, especially since it's not much code wasted anyway.

2024-06-03 15:51 UTC, skorokithakis approved these changes

2024-06-03 15:51 UTC, skorokithakis commented
Looks good, thanks! Can you please also fix the precommit errors?

2024-06-04 09:44 UTC, maximeflya commented
The workflow run did not contain the `pyproject.toml` file that defines the 120 character line length

2024-06-07 07:40 UTC, skorokithakis commented
Since the linter changed a bunch of things, I'd like to run it myself to verify the changes. I'll hopefully get to it in the next few days, and then merge, thank you!

2024-06-10 09:44 UTC, closed without merging